package edu.eci.cosw.samples.model;

// Generated Feb 5, 2013 5:52:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AlmClientes generated by hbm2java
 */
@Entity
@Table(name = "ALM_CLIENTES" )
public class Cliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idcliente;
	private String nombre;
	private String direccion;
	private String telefono;

	public Cliente() {
	}

	public Cliente(int idcliente, String nombre, String direccion,
			String telefono) {
		this.idcliente = idcliente;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
	}

	public Cliente(int idcliente, String nombre, String direccion,
			String telefono, Set<Pedido> almPedidoses) {
		this.idcliente = idcliente;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
	}

	@Id
	@Column(name = "idcliente", unique = true, nullable = false)
	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", nullable = false, length = 45)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", nullable = false, length = 45)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}



}
