package edu.eci.cosw.samples.model;

// Generated Feb 5, 2013 5:52:11 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AlmDespachos generated by hbm2java
 */
@Entity
@Table(name = "ALM_DESPACHOS" )
public class Despacho implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2544678631302988300L;
	private Integer iddespacho;
	private Pedido almPedidos;
	private Vehiculo almVehiculos;
	private Blob qrcode;

	public Despacho() {
	}

	public Despacho(Pedido almPedidos, Vehiculo almVehiculos) {
		this.almPedidos = almPedidos;
		this.almVehiculos = almVehiculos;
	}

	public Despacho(Pedido almPedidos, Vehiculo almVehiculos,
			Blob qrcode) {
		this.almPedidos = almPedidos;
		this.almVehiculos = almVehiculos;
		this.qrcode = qrcode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "iddespacho", unique = true, nullable = false)
	public Integer getIddespacho() {
		return this.iddespacho;
	}

	public void setIddespacho(Integer iddespacho) {
		this.iddespacho = iddespacho;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PEDIDOS_idpedido", nullable = false)
	public Pedido getPedidos() {
		return this.almPedidos;
	}

	public void setPedidos(Pedido almPedidos) {
		this.almPedidos = almPedidos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VEHICULOS_placa", nullable = false)
	public Vehiculo getVehiculo() {
		return this.almVehiculos;
	}

	public void setVehiculo(Vehiculo almVehiculos) {
		this.almVehiculos = almVehiculos;
	}

	@Column(name = "qrcode")
	public Blob getQrcode() {
		return this.qrcode;
	}

	public void setQrcode(Blob qrcode) {
		this.qrcode = qrcode;
	}

}
